version: '2.1'

volumes:
  cassandra_data:
    driver: local
    
services:
  consul:
    image: progrium/consul:latest
    container_name: consul
    command: -server -bootstrap -ui-dir /ui
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8500 || exit 1"]
      interval: 5s
      retries: 10
    ports:
      - 8500:8500
    expose:
      - 53
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
    dns:
      - 127.0.0.1

  kong-database:
    image: cassandra:3
    container_name: kong-db
    restart: on-failure
    volumes:
    ports:
      - 9042:9042
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 10s
      timeout: 5s
      retries: 10

  kong-migration:
    image: kong
    container_name: kong-db-migration
    restart: on-failure
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      - KONG_DATABASE=cassandra
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
    command: kong migrations up
    

  kong:
    build: kong/
    container_name: kong
    depends_on:
      kong-database:
        condition: service_healthy
      kong-migration:
        condition: service_started
    environment:
      - KONG_DATABASE=cassandra
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    links:
      - consul:consul
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    expose:
      - 8000
      - 8001
      - 8443
      - 8444
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8000 || exit 1"]
      interval: 5s
      retries: 10
      
  kong-ui:
    image: pantsel/konga
    container_name: kong-ui
    depends_on:
      kong:
        condition: service_healthy
    ports:
      - 1337:1337
    expose:
      - 1337
    environment:
      - NODE_ENV=development
