version: '2.1'
    
services:
      
  kong-ui:
    image: pantsel/konga
    container_name: kong-ui
    ports:
      - 1337:1337
    expose:
      - 1337
    environment:
      - NODE_ENV=development
